name: LemonCommonLib
version: '${project.version}'
main: me.lemonypancakes.bukkit.common.LemonCommonLib
api-version: 1.17
load: STARTUP
softdepend:
  - PacketWrapper
  - ProtocolLib
authors: [ LemonyPancakes ]
description: A collection of libraries.
